// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wallet.Api.Data;

#nullable disable

namespace Wallet.Api.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    partial class WalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerCommission.Messaging.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("PartnerCommission.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Wallet.Domain.Entities.Accrual", b =>
                {
                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_id");

                    b.Property<DateTimeOffset>("AccruedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accrued_at");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<string>("EventExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_external_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_id");

                    b.Property<int>("SchemaType")
                        .HasColumnType("integer")
                        .HasColumnName("schema_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UserExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_external_id");

                    b.HasKey("CommissionId")
                        .HasName("pk_accruals");

                    b.HasIndex("PayoutId")
                        .HasDatabaseName("ix_accruals_payout_id");

                    b.HasIndex("UserExternalId")
                        .HasDatabaseName("ix_accruals_pending_user")
                        .HasFilter("status = 1");

                    b.ToTable("accruals", (string)null);
                });

            modelBuilder.Entity("Wallet.Domain.Entities.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<int>("CommissionCount")
                        .HasColumnType("integer")
                        .HasColumnName("commission_count");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("UserExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_external_id");

                    b.HasKey("Id")
                        .HasName("pk_payouts");

                    b.HasIndex("UserExternalId", "PaidAt")
                        .HasDatabaseName("ix_payouts_user_external_id_paid_at");

                    b.ToTable("payouts", (string)null);
                });

            modelBuilder.Entity("Wallet.Domain.Entities.UserWallet", b =>
                {
                    b.Property<string>("UserExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_external_id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserExternalId")
                        .HasName("pk_wallets");

                    b.ToTable("wallets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
